openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    $ref: '.~1paths~1pets.yml'
  /pets/{petId}:
    $ref: '.~1paths~1pet.yml'
components:
  schemas:
    Pet:
      $ref: '.~1components~1pet.yml'
    Pets:
      $ref: '.~1components~1pets.yml'
    Error:
      $ref: '.~1components~1error.yml'
